name: release
on:
  push:
    branches:
      - release
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'

      - run: npm ci
      - run: npm run test:coverage
      - run: npx --yes jest-coverage-badges
      - run: npm run lint -- --fix

      - run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"

      - run: npm --no-git-tag-version version prerelease -preid=alpha
      - run: npm run pack
      - run: npm publish ./dist
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Backsync with master
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: master

      - name: Build docs
        run: |
          npm run build_docs
          mkdir -p artifacts/lib
          cp -r dist_doc artifacts/lib/docs
          cp -r coverage artifacts/lib/coverage

      - name: Copy artifacts to site repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          SSH_DEPLOY_KEY: ${{ secrets.SITE_PUBLISH_PRIVATE_KEY }}

        with:
          source-directory: artifacts/lib
          target-directory: artifacts/lib
          destination-github-username: john-smith-library
          destination-repository-name: john-smith-library.github.io
          user-email: <>
