name: release
on:
  push:
    branches:
      - release
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - run: npm run test

      - name: Tutorial->Init
        run: npm ci
        working-directory: ./src_tutorial

      - run: npm run build_samples_code
        working-directory: ./src_tutorial

      - run: npm run build_site
        working-directory: ./src_tutorial

      - run: npm run pack
      - run: npm publish ./dist
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
